import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
    fontFamily: "var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif)",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    borderBottom: "1px solid",
    padding: "0 1rem",
    height: 44,
    flexShrink: 0,
    gap: "0.5rem",
  },
  logo: {
    fontWeight: 600,
    fontSize: "0.85rem",
    marginRight: "0.5rem",
  },
  tabGroup: {
    display: "flex",
    gap: 0,
  },
  tabBtn: {
    padding: "0.5rem 0.75rem",
    fontSize: "0.8rem",
    background: "none",
    border: "none",
    borderBottom: "2px solid",
    cursor: "pointer",
    lineHeight: "28px",
    fontFamily: "inherit",
  },
  mainLayout: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
  },
  leftPanel: {
    width: 280,
    minWidth: 220,
    maxWidth: 360,
    borderRight: "1px solid",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  listHeader: {
    padding: "0.75rem",
    flexShrink: 0,
  },
  listScroll: {
    flex: 1,
    overflowY: "auto",
  },
  listItem: {
    padding: "0.65rem 0.75rem",
    borderBottom: "1px solid",
    cursor: "pointer",
    transition: "background 0.1s",
  },
  rightPanel: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    padding: "clamp(0rem, 2.5vw, 1.25rem)",
    overflow: "hidden",
  },
  previewFrame: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    border: "1px solid",
    borderRadius: 10,
    overflow: "hidden",
    boxShadow: "0 1px 2px rgba(15, 23, 42, 0.04), 0 8px 24px rgba(15, 23, 42, 0.06)",
  },
  previewHeader: {
    height: 36,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 0.75rem",
    borderBottom: "1px solid",
    fontSize: "0.72rem",
    letterSpacing: "0.01em",
  },
  previewHeaderLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    minWidth: 0,
    flex: 1,
  },
  previewHeaderName: {
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontWeight: 500,
    fontSize: "0.76rem",
    letterSpacing: "0",
  },
  previewDownload: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: 6,
    textDecoration: "none",
    flexShrink: 0,
    transition: "background 120ms ease, color 120ms ease",
  },
  previewBody: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  previewStatus: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.82rem",
    padding: "1.5rem",
    textAlign: "center",
  },
  settingsOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.3)",
    zIndex: 90,
    display: "flex",
    justifyContent: "flex-end",
  },
  settingsPanel: {
    width: 400,
    maxWidth: "90vw",
    height: "100%",
    borderLeft: "1px solid",
    padding: "1.5rem",
    overflowY: "auto",
    boxShadow: "-4px 0 20px rgba(0,0,0,0.1)",
  },
  sectionTitle: {
    fontSize: "0.7rem",
    textTransform: "uppercase",
    letterSpacing: "1px",
    fontWeight: 600,
    margin: "0.5rem 0",
  },
  textarea: {
    width: "100%",
    padding: "0.5rem 0.6rem",
    borderRadius: 6,
    border: "1px solid",
    fontSize: "0.8rem",
    fontFamily: "inherit",
    outline: "none",
    minHeight: 140,
    resize: "vertical",
  },
  assetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
    gap: "0.5rem",
  },
  assetCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0.5rem",
    borderRadius: 8,
    border: "1px solid",
    gap: "0.25rem",
  },
  assetThumb: {
    width: 56,
    height: 56,
    borderRadius: 4,
  },
  dashed: {
    border: "2px dashed",
    justifyContent: "center",
    minHeight: 80,
    fontSize: "0.82rem",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dialog: {
    border: "1px solid",
    borderRadius: 12,
    padding: "1.5rem",
    width: 360,
    maxWidth: "90vw",
    boxShadow: "0 8px 30px rgba(0,0,0,0.2)",
  },
  templateOpt: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.45rem 0.6rem",
    border: "1px solid",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: "0.8rem",
  },
  label: {
    display: "block",
    fontSize: "0.75rem",
    marginBottom: "0.2rem",
  },
  input: {
    width: "100%",
    padding: "0.45rem 0.6rem",
    borderRadius: 6,
    border: "1px solid",
    fontSize: "0.8rem",
    fontFamily: "inherit",
    outline: "none",
  },
  btn: {
    padding: "0.4rem 0.85rem",
    borderRadius: 6,
    border: "none",
    fontSize: "0.78rem",
    cursor: "pointer",
    fontWeight: 500,
    whiteSpace: "nowrap",
    fontFamily: "inherit",
  },
  btnPrimary: {
    color: "#fff",
  },
  btnGhost: {
    background: "none",
    border: "1px solid",
  },
  smallBtn: {
    padding: "0.15rem 0.4rem",
    borderRadius: 4,
    border: "1px solid",
    fontSize: "0.68rem",
    cursor: "pointer",
    background: "none",
    fontFamily: "inherit",
  },
};
